-- =============================================================================
-- NebulaX Railway Track Access Optimisation
-- 03_seed_init.sql: Seed Initial Problem Data & Temporal Dimension
-- =============================================================================

SET search_path TO nebula, public;

-- 1. LINES
INSERT INTO lines (line_code, line_name) VALUES ('ALP', 'Line Alpha') ON CONFLICT (line_code) DO NOTHING;
INSERT INTO lines (line_code, line_name) VALUES ('BET', 'Line Beta') ON CONFLICT (line_code) DO NOTHING;

-- 2. STATIONS
INSERT INTO stations (station_id, line_code, seq, is_interchange) VALUES ('S01', 'ALP', 1, FALSE) ON CONFLICT (station_id, line_code) DO NOTHING;
INSERT INTO stations (station_id, line_code, seq, is_interchange) VALUES ('S02', 'ALP', 2, FALSE) ON CONFLICT (station_id, line_code) DO NOTHING;
INSERT INTO stations (station_id, line_code, seq, is_interchange) VALUES ('S03', 'ALP', 3, FALSE) ON CONFLICT (station_id, line_code) DO NOTHING;
INSERT INTO stations (station_id, line_code, seq, is_interchange) VALUES ('S04', 'ALP', 4, FALSE) ON CONFLICT (station_id, line_code) DO NOTHING;
INSERT INTO stations (station_id, line_code, seq, is_interchange) VALUES ('H01', 'ALP', 5, TRUE) ON CONFLICT (station_id, line_code) DO NOTHING;
INSERT INTO stations (station_id, line_code, seq, is_interchange) VALUES ('H02', 'ALP', 6, TRUE) ON CONFLICT (station_id, line_code) DO NOTHING;
INSERT INTO stations (station_id, line_code, seq, is_interchange) VALUES ('S05', 'ALP', 7, FALSE) ON CONFLICT (station_id, line_code) DO NOTHING;
INSERT INTO stations (station_id, line_code, seq, is_interchange) VALUES ('S06', 'ALP', 8, FALSE) ON CONFLICT (station_id, line_code) DO NOTHING;
INSERT INTO stations (station_id, line_code, seq, is_interchange) VALUES ('S07', 'ALP', 9, FALSE) ON CONFLICT (station_id, line_code) DO NOTHING;
INSERT INTO stations (station_id, line_code, seq, is_interchange) VALUES ('S08', 'ALP', 10, FALSE) ON CONFLICT (station_id, line_code) DO NOTHING;
INSERT INTO stations (station_id, line_code, seq, is_interchange) VALUES ('S11', 'BET', 1, FALSE) ON CONFLICT (station_id, line_code) DO NOTHING;
INSERT INTO stations (station_id, line_code, seq, is_interchange) VALUES ('S12', 'BET', 2, FALSE) ON CONFLICT (station_id, line_code) DO NOTHING;
INSERT INTO stations (station_id, line_code, seq, is_interchange) VALUES ('S13', 'BET', 3, FALSE) ON CONFLICT (station_id, line_code) DO NOTHING;
INSERT INTO stations (station_id, line_code, seq, is_interchange) VALUES ('S14', 'BET', 4, FALSE) ON CONFLICT (station_id, line_code) DO NOTHING;
INSERT INTO stations (station_id, line_code, seq, is_interchange) VALUES ('H01', 'BET', 5, TRUE) ON CONFLICT (station_id, line_code) DO NOTHING;
INSERT INTO stations (station_id, line_code, seq, is_interchange) VALUES ('H02', 'BET', 6, TRUE) ON CONFLICT (station_id, line_code) DO NOTHING;
INSERT INTO stations (station_id, line_code, seq, is_interchange) VALUES ('S15', 'BET', 7, FALSE) ON CONFLICT (station_id, line_code) DO NOTHING;
INSERT INTO stations (station_id, line_code, seq, is_interchange) VALUES ('S16', 'BET', 8, FALSE) ON CONFLICT (station_id, line_code) DO NOTHING;
INSERT INTO stations (station_id, line_code, seq, is_interchange) VALUES ('S17', 'BET', 9, FALSE) ON CONFLICT (station_id, line_code) DO NOTHING;
INSERT INTO stations (station_id, line_code, seq, is_interchange) VALUES ('S18', 'BET', 10, FALSE) ON CONFLICT (station_id, line_code) DO NOTHING;

-- 3. SECTORS
INSERT INTO sectors (sector_id, line_code, from_station_id, to_station_id, seq, is_shared) VALUES ('SEC:ALP:S01_S02', 'ALP', 'S01', 'S02', 1, FALSE) ON CONFLICT (sector_id) DO NOTHING;
INSERT INTO sectors (sector_id, line_code, from_station_id, to_station_id, seq, is_shared) VALUES ('SEC:ALP:S02_S03', 'ALP', 'S02', 'S03', 2, FALSE) ON CONFLICT (sector_id) DO NOTHING;
INSERT INTO sectors (sector_id, line_code, from_station_id, to_station_id, seq, is_shared) VALUES ('SEC:ALP:S03_S04', 'ALP', 'S03', 'S04', 3, FALSE) ON CONFLICT (sector_id) DO NOTHING;
INSERT INTO sectors (sector_id, line_code, from_station_id, to_station_id, seq, is_shared) VALUES ('SEC:ALP:S04_H01', 'ALP', 'S04', 'H01', 4, FALSE) ON CONFLICT (sector_id) DO NOTHING;
INSERT INTO sectors (sector_id, line_code, from_station_id, to_station_id, seq, is_shared) VALUES ('SEC:ALP:H01_H02', 'ALP', 'H01', 'H02', 5, FALSE) ON CONFLICT (sector_id) DO NOTHING;
INSERT INTO sectors (sector_id, line_code, from_station_id, to_station_id, seq, is_shared) VALUES ('SEC:ALP:H02_S05', 'ALP', 'H02', 'S05', 6, FALSE) ON CONFLICT (sector_id) DO NOTHING;
INSERT INTO sectors (sector_id, line_code, from_station_id, to_station_id, seq, is_shared) VALUES ('SEC:ALP:S05_S06', 'ALP', 'S05', 'S06', 7, FALSE) ON CONFLICT (sector_id) DO NOTHING;
INSERT INTO sectors (sector_id, line_code, from_station_id, to_station_id, seq, is_shared) VALUES ('SEC:ALP:S06_S07', 'ALP', 'S06', 'S07', 8, FALSE) ON CONFLICT (sector_id) DO NOTHING;
INSERT INTO sectors (sector_id, line_code, from_station_id, to_station_id, seq, is_shared) VALUES ('SEC:ALP:S07_S08', 'ALP', 'S07', 'S08', 9, FALSE) ON CONFLICT (sector_id) DO NOTHING;
INSERT INTO sectors (sector_id, line_code, from_station_id, to_station_id, seq, is_shared) VALUES ('SEC:BET:S11_S12', 'BET', 'S11', 'S12', 10, FALSE) ON CONFLICT (sector_id) DO NOTHING;
INSERT INTO sectors (sector_id, line_code, from_station_id, to_station_id, seq, is_shared) VALUES ('SEC:BET:S12_S13', 'BET', 'S12', 'S13', 11, FALSE) ON CONFLICT (sector_id) DO NOTHING;
INSERT INTO sectors (sector_id, line_code, from_station_id, to_station_id, seq, is_shared) VALUES ('SEC:BET:S13_S14', 'BET', 'S13', 'S14', 12, FALSE) ON CONFLICT (sector_id) DO NOTHING;
INSERT INTO sectors (sector_id, line_code, from_station_id, to_station_id, seq, is_shared) VALUES ('SEC:BET:S14_H01', 'BET', 'S14', 'H01', 13, FALSE) ON CONFLICT (sector_id) DO NOTHING;
INSERT INTO sectors (sector_id, line_code, from_station_id, to_station_id, seq, is_shared) VALUES ('SEC:BET:H01_H02', 'BET', 'H01', 'H02', 14, FALSE) ON CONFLICT (sector_id) DO NOTHING;
INSERT INTO sectors (sector_id, line_code, from_station_id, to_station_id, seq, is_shared) VALUES ('SEC:BET:H02_S15', 'BET', 'H02', 'S15', 15, FALSE) ON CONFLICT (sector_id) DO NOTHING;
INSERT INTO sectors (sector_id, line_code, from_station_id, to_station_id, seq, is_shared) VALUES ('SEC:BET:S15_S16', 'BET', 'S15', 'S16', 16, FALSE) ON CONFLICT (sector_id) DO NOTHING;
INSERT INTO sectors (sector_id, line_code, from_station_id, to_station_id, seq, is_shared) VALUES ('SEC:BET:S16_S17', 'BET', 'S16', 'S17', 17, FALSE) ON CONFLICT (sector_id) DO NOTHING;
INSERT INTO sectors (sector_id, line_code, from_station_id, to_station_id, seq, is_shared) VALUES ('SEC:BET:S17_S18', 'BET', 'S17', 'S18', 18, FALSE) ON CONFLICT (sector_id) DO NOTHING;

-- 4. LOCATION_SUPPLY
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:ALP:S01_S02:EB', 'tunnel sector', 'ALP', 'EB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:ALP:S01_S02:WB', 'tunnel sector', 'ALP', 'WB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:ALP:S02_S03:EB', 'tunnel sector', 'ALP', 'EB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:ALP:S02_S03:WB', 'tunnel sector', 'ALP', 'WB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:ALP:S03_S04:EB', 'tunnel sector', 'ALP', 'EB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:ALP:S03_S04:WB', 'tunnel sector', 'ALP', 'WB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:ALP:S04_H01:EB', 'tunnel sector', 'ALP', 'EB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:ALP:S04_H01:WB', 'tunnel sector', 'ALP', 'WB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:ALP:H01_H02:EB', 'tunnel sector', 'ALP', 'EB', 1) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:ALP:H01_H02:WB', 'tunnel sector', 'ALP', 'WB', 1) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:ALP:H02_S05:EB', 'tunnel sector', 'ALP', 'EB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:ALP:H02_S05:WB', 'tunnel sector', 'ALP', 'WB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:ALP:S05_S06:EB', 'tunnel sector', 'ALP', 'EB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:ALP:S05_S06:WB', 'tunnel sector', 'ALP', 'WB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:ALP:S06_S07:EB', 'tunnel sector', 'ALP', 'EB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:ALP:S06_S07:WB', 'tunnel sector', 'ALP', 'WB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:ALP:S07_S08:EB', 'tunnel sector', 'ALP', 'EB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:ALP:S07_S08:WB', 'tunnel sector', 'ALP', 'WB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:BET:S11_S12:EB', 'tunnel sector', 'BET', 'EB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:BET:S11_S12:WB', 'tunnel sector', 'BET', 'WB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:BET:S12_S13:EB', 'tunnel sector', 'BET', 'EB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:BET:S12_S13:WB', 'tunnel sector', 'BET', 'WB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:BET:S13_S14:EB', 'tunnel sector', 'BET', 'EB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:BET:S13_S14:WB', 'tunnel sector', 'BET', 'WB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:BET:S14_H01:EB', 'tunnel sector', 'BET', 'EB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:BET:S14_H01:WB', 'tunnel sector', 'BET', 'WB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:BET:H01_H02:EB', 'tunnel sector', 'BET', 'EB', 1) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:BET:H01_H02:WB', 'tunnel sector', 'BET', 'WB', 1) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:BET:H02_S15:EB', 'tunnel sector', 'BET', 'EB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:BET:H02_S15:WB', 'tunnel sector', 'BET', 'WB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:BET:S15_S16:EB', 'tunnel sector', 'BET', 'EB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:BET:S15_S16:WB', 'tunnel sector', 'BET', 'WB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:BET:S16_S17:EB', 'tunnel sector', 'BET', 'EB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:BET:S16_S17:WB', 'tunnel sector', 'BET', 'WB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:BET:S17_S18:EB', 'tunnel sector', 'BET', 'EB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('SEC:BET:S17_S18:WB', 'tunnel sector', 'BET', 'WB', 4) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:ALP:S01:EB', 'platform sector', 'ALP', 'EB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:ALP:S01:WB', 'platform sector', 'ALP', 'WB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:ALP:S02:EB', 'platform sector', 'ALP', 'EB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:ALP:S02:WB', 'platform sector', 'ALP', 'WB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:ALP:S03:EB', 'platform sector', 'ALP', 'EB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:ALP:S03:WB', 'platform sector', 'ALP', 'WB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:ALP:S04:EB', 'platform sector', 'ALP', 'EB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:ALP:S04:WB', 'platform sector', 'ALP', 'WB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:ALP:H01:EB', 'platform sector', 'ALP', 'EB', 1) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:ALP:H01:WB', 'platform sector', 'ALP', 'WB', 1) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:ALP:H02:EB', 'platform sector', 'ALP', 'EB', 1) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:ALP:H02:WB', 'platform sector', 'ALP', 'WB', 1) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:ALP:S05:EB', 'platform sector', 'ALP', 'EB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:ALP:S05:WB', 'platform sector', 'ALP', 'WB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:ALP:S06:EB', 'platform sector', 'ALP', 'EB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:ALP:S06:WB', 'platform sector', 'ALP', 'WB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:ALP:S07:EB', 'platform sector', 'ALP', 'EB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:ALP:S07:WB', 'platform sector', 'ALP', 'WB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:ALP:S08:EB', 'platform sector', 'ALP', 'EB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:ALP:S08:WB', 'platform sector', 'ALP', 'WB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:BET:S11:EB', 'platform sector', 'BET', 'EB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:BET:S11:WB', 'platform sector', 'BET', 'WB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:BET:S12:EB', 'platform sector', 'BET', 'EB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:BET:S12:WB', 'platform sector', 'BET', 'WB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:BET:S13:EB', 'platform sector', 'BET', 'EB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:BET:S13:WB', 'platform sector', 'BET', 'WB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:BET:S14:EB', 'platform sector', 'BET', 'EB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:BET:S14:WB', 'platform sector', 'BET', 'WB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:BET:H01:EB', 'platform sector', 'BET', 'EB', 1) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:BET:H01:WB', 'platform sector', 'BET', 'WB', 1) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:BET:H02:EB', 'platform sector', 'BET', 'EB', 1) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:BET:H02:WB', 'platform sector', 'BET', 'WB', 1) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:BET:S15:EB', 'platform sector', 'BET', 'EB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:BET:S15:WB', 'platform sector', 'BET', 'WB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:BET:S16:EB', 'platform sector', 'BET', 'EB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:BET:S16:WB', 'platform sector', 'BET', 'WB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:BET:S17:EB', 'platform sector', 'BET', 'EB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:BET:S17:WB', 'platform sector', 'BET', 'WB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:BET:S18:EB', 'platform sector', 'BET', 'EB', 2) ON CONFLICT (location_id) DO NOTHING;
INSERT INTO location_supply (location_id, location_kind, line_code, bound, supply_capacity) VALUES ('PLAT:BET:S18:WB', 'platform sector', 'BET', 'WB', 2) ON CONFLICT (location_id) DO NOTHING;

-- 5. BUFFER_RULES
INSERT INTO buffer_rules (nature_of_works, up_to_buffer_sectors, opposite_bound_required) VALUES ('Live', 2, TRUE) ON CONFLICT (nature_of_works) DO NOTHING;
INSERT INTO buffer_rules (nature_of_works, up_to_buffer_sectors, opposite_bound_required) VALUES ('Non-live (Consist)', 1, FALSE) ON CONFLICT (nature_of_works) DO NOTHING;
INSERT INTO buffer_rules (nature_of_works, up_to_buffer_sectors, opposite_bound_required) VALUES ('Non-live (Others)', 0, FALSE) ON CONFLICT (nature_of_works) DO NOTHING;

-- 6. SYSTEM_PARAMETERS
INSERT INTO system_parameters (param_key, param_value, description) VALUES ('horizon_start', '2027-01-04', 'System parameter horizon_start') ON CONFLICT (param_key) DO UPDATE SET param_value = EXCLUDED.param_value;
INSERT INTO system_parameters (param_key, param_value, description) VALUES ('horizon_weeks', '30', 'System parameter horizon_weeks') ON CONFLICT (param_key) DO UPDATE SET param_value = EXCLUDED.param_value;

-- 7. DIM_CALENDAR_WEEKS (Dynamically populated from horizon parameters)
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (1, '2027-01-04', '2027-01-10') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (2, '2027-01-11', '2027-01-17') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (3, '2027-01-18', '2027-01-24') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (4, '2027-01-25', '2027-01-31') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (5, '2027-02-01', '2027-02-07') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (6, '2027-02-08', '2027-02-14') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (7, '2027-02-15', '2027-02-21') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (8, '2027-02-22', '2027-02-28') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (9, '2027-03-01', '2027-03-07') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (10, '2027-03-08', '2027-03-14') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (11, '2027-03-15', '2027-03-21') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (12, '2027-03-22', '2027-03-28') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (13, '2027-03-29', '2027-04-04') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (14, '2027-04-05', '2027-04-11') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (15, '2027-04-12', '2027-04-18') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (16, '2027-04-19', '2027-04-25') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (17, '2027-04-26', '2027-05-02') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (18, '2027-05-03', '2027-05-09') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (19, '2027-05-10', '2027-05-16') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (20, '2027-05-17', '2027-05-23') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (21, '2027-05-24', '2027-05-30') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (22, '2027-05-31', '2027-06-06') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (23, '2027-06-07', '2027-06-13') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (24, '2027-06-14', '2027-06-20') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (25, '2027-06-21', '2027-06-27') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (26, '2027-06-28', '2027-07-04') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (27, '2027-07-05', '2027-07-11') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (28, '2027-07-12', '2027-07-18') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (29, '2027-07-19', '2027-07-25') ON CONFLICT (week_number) DO NOTHING;
INSERT INTO dim_calendar_weeks (week_number, start_date, end_date) VALUES (30, '2027-07-26', '2027-08-01') ON CONFLICT (week_number) DO NOTHING;

-- 8. CONTRACTS
INSERT INTO contracts (contract_number, contract_description, contract_award_date, activity_type, nature_of_activity, contract_priority, contract_completion_date, planned_completion_date, number_of_workfronts, access_type, number_of_maximum_access_per_week) VALUES ('C001', 'Renewal programme 1', '2026-10-02', 'Renewal', 'Non-live (Consist)', 3, '2027-08-01', '2027-06-13', 2, 'C', 3) ON CONFLICT (contract_number) DO NOTHING;
INSERT INTO contracts (contract_number, contract_description, contract_award_date, activity_type, nature_of_activity, contract_priority, contract_completion_date, planned_completion_date, number_of_workfronts, access_type, number_of_maximum_access_per_week) VALUES ('C002', 'Renewal programme 2', '2026-06-25', 'Renewal', 'Non-live (Consist)', 2, '2027-08-08', '2027-07-04', 1, 'C', 3) ON CONFLICT (contract_number) DO NOTHING;
INSERT INTO contracts (contract_number, contract_description, contract_award_date, activity_type, nature_of_activity, contract_priority, contract_completion_date, planned_completion_date, number_of_workfronts, access_type, number_of_maximum_access_per_week) VALUES ('C003', 'Construction programme 3', '2026-02-01', 'Construction', 'Non-live (Others)', 1, '2027-07-18', '2027-07-04', 1, 'C', 3) ON CONFLICT (contract_number) DO NOTHING;
INSERT INTO contracts (contract_number, contract_description, contract_award_date, activity_type, nature_of_activity, contract_priority, contract_completion_date, planned_completion_date, number_of_workfronts, access_type, number_of_maximum_access_per_week) VALUES ('C004', 'Renewal programme 4', '2026-01-16', 'Renewal', 'Non-live (Consist)', 1, '2027-08-08', '2027-07-25', 1, 'PC', 3) ON CONFLICT (contract_number) DO NOTHING;
INSERT INTO contracts (contract_number, contract_description, contract_award_date, activity_type, nature_of_activity, contract_priority, contract_completion_date, planned_completion_date, number_of_workfronts, access_type, number_of_maximum_access_per_week) VALUES ('C005', 'Renewal programme 5', '2026-10-25', 'Renewal', 'Non-live (Consist)', 3, '2027-08-22', '2027-03-21', 2, 'PC', 3) ON CONFLICT (contract_number) DO NOTHING;
INSERT INTO contracts (contract_number, contract_description, contract_award_date, activity_type, nature_of_activity, contract_priority, contract_completion_date, planned_completion_date, number_of_workfronts, access_type, number_of_maximum_access_per_week) VALUES ('C006', 'Construction programme 6', '2026-07-12', 'Construction', 'Non-live (Others)', 3, '2027-08-15', '2027-07-04', 1, 'C', 3) ON CONFLICT (contract_number) DO NOTHING;
INSERT INTO contracts (contract_number, contract_description, contract_award_date, activity_type, nature_of_activity, contract_priority, contract_completion_date, planned_completion_date, number_of_workfronts, access_type, number_of_maximum_access_per_week) VALUES ('C007', 'Renewal programme 7', '2026-01-13', 'Renewal', 'Non-live (Consist)', 1, '2027-07-25', '2027-07-11', 1, 'C', 3) ON CONFLICT (contract_number) DO NOTHING;
INSERT INTO contracts (contract_number, contract_description, contract_award_date, activity_type, nature_of_activity, contract_priority, contract_completion_date, planned_completion_date, number_of_workfronts, access_type, number_of_maximum_access_per_week) VALUES ('C008', 'Renewal programme 8', '2026-08-03', 'Renewal', 'Non-live (Consist)', 3, '2027-08-22', '2027-07-18', 1, 'C', 3) ON CONFLICT (contract_number) DO NOTHING;
INSERT INTO contracts (contract_number, contract_description, contract_award_date, activity_type, nature_of_activity, contract_priority, contract_completion_date, planned_completion_date, number_of_workfronts, access_type, number_of_maximum_access_per_week) VALUES ('C009', 'Construction programme 9', '2026-02-09', 'Construction', 'Non-live (Others)', 3, '2027-07-25', '2027-06-27', 1, 'PC', 3) ON CONFLICT (contract_number) DO NOTHING;
INSERT INTO contracts (contract_number, contract_description, contract_award_date, activity_type, nature_of_activity, contract_priority, contract_completion_date, planned_completion_date, number_of_workfronts, access_type, number_of_maximum_access_per_week) VALUES ('C010', 'Construction programme 10', '2026-05-18', 'Construction', 'Non-live (Others)', 3, '2027-07-25', '2027-05-16', 2, 'C', 3) ON CONFLICT (contract_number) DO NOTHING;
INSERT INTO contracts (contract_number, contract_description, contract_award_date, activity_type, nature_of_activity, contract_priority, contract_completion_date, planned_completion_date, number_of_workfronts, access_type, number_of_maximum_access_per_week) VALUES ('C011', 'Renewal programme 11', '2026-04-20', 'Renewal', 'Non-live (Consist)', 2, '2027-08-15', '2027-07-11', 1, 'C', 3) ON CONFLICT (contract_number) DO NOTHING;
INSERT INTO contracts (contract_number, contract_description, contract_award_date, activity_type, nature_of_activity, contract_priority, contract_completion_date, planned_completion_date, number_of_workfronts, access_type, number_of_maximum_access_per_week) VALUES ('C012', 'Construction programme 12', '2026-06-07', 'Construction', 'Non-live (Others)', 1, '2027-07-25', '2027-07-11', 1, 'C', 3) ON CONFLICT (contract_number) DO NOTHING;
INSERT INTO contracts (contract_number, contract_description, contract_award_date, activity_type, nature_of_activity, contract_priority, contract_completion_date, planned_completion_date, number_of_workfronts, access_type, number_of_maximum_access_per_week) VALUES ('C013', 'Live-rail renewal programme 13', '2026-03-10', 'Renewal', 'Live', 2, '2027-08-01', '2027-05-30', 1, 'PC', 2) ON CONFLICT (contract_number) DO NOTHING;
INSERT INTO contracts (contract_number, contract_description, contract_award_date, activity_type, nature_of_activity, contract_priority, contract_completion_date, planned_completion_date, number_of_workfronts, access_type, number_of_maximum_access_per_week) VALUES ('C014', 'Live-rail construction programme 14', '2026-05-05', 'Construction', 'Live', 3, '2027-08-15', '2027-07-18', 1, 'PM', 2) ON CONFLICT (contract_number) DO NOTHING;

-- 9. ACTIVITIES
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A001', 'C001', 'Renewal', 'SEC:BET:S15_S16:EB', 'SEC:BET:S16_S17:EB', 2, '2027-05-24', NULL, 2) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A002', 'C001', 'Renewal', 'SEC:BET:S11_S12:WB', 'SEC:BET:S12_S13:WB', 1, '2027-01-04', NULL, 3) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A003', 'C001', 'Renewal', 'SEC:BET:H01_H02:EB', 'SEC:BET:S15_S16:EB', 5, '2027-03-15', NULL, 1) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A004', 'C001', 'Renewal', 'SEC:ALP:S03_S04:EB', 'SEC:ALP:S04_H01:EB', 3, '2027-04-12', 'A003', 2) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A006', 'C001', 'Renewal', 'SEC:ALP:S03_S04:WB', 'SEC:ALP:H01_H02:WB', 2, '2027-01-11', NULL, 2) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A007', 'C001', 'Renewal', 'SEC:BET:H01_H02:EB', 'SEC:BET:H01_H02:EB', 7, '2027-04-12', NULL, 1) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A008', 'C002', 'Renewal', 'SEC:BET:S17_S18:EB', 'SEC:BET:S17_S18:EB', 5, '2027-04-19', NULL, 1) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A009', 'C002', 'Renewal', 'SEC:ALP:S05_S06:EB', 'SEC:ALP:S05_S06:EB', 7, '2027-01-11', NULL, 3) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A011', 'C002', 'Renewal', 'SEC:BET:S15_S16:EB', 'SEC:BET:S16_S17:EB', 2, '2027-04-12', NULL, 2) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A012', 'C002', 'Renewal', 'SEC:BET:H01_H02:WB', 'SEC:BET:H02_S15:WB', 7, '2027-01-11', NULL, 1) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A013', 'C002', 'Renewal', 'SEC:ALP:S05_S06:WB', 'SEC:ALP:S05_S06:WB', 5, '2027-05-24', 'A012', 2) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A014', 'C003', 'Construction', 'SEC:ALP:S07_S08:EB', 'SEC:ALP:S07_S08:EB', 7, '2027-03-29', NULL, 3) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A017', 'C003', 'Construction', 'SEC:BET:H01_H02:EB', 'SEC:BET:S15_S16:EB', 7, '2027-04-26', NULL, 2) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A019', 'C003', 'Construction', 'SEC:BET:S16_S17:EB', 'SEC:BET:S16_S17:EB', 2, '2027-03-15', NULL, 3) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A020', 'C003', 'Construction', 'SEC:ALP:S04_H01:WB', 'SEC:ALP:H02_S05:WB', 2, '2027-03-29', NULL, 2) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A021', 'C004', 'Renewal', 'SEC:BET:S11_S12:WB', 'SEC:BET:S12_S13:WB', 3, '2027-01-18', NULL, 2) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A023', 'C004', 'Renewal', 'SEC:ALP:S03_S04:WB', 'SEC:ALP:S03_S04:WB', 7, '2027-05-24', NULL, 1) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A025', 'C004', 'Renewal', 'SEC:ALP:S01_S02:EB', 'SEC:ALP:S02_S03:EB', 7, '2027-02-22', NULL, 1) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A028', 'C005', 'Renewal', 'SEC:ALP:S03_S04:EB', 'SEC:ALP:S04_H01:EB', 2, '2027-03-01', NULL, 2) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A031', 'C005', 'Renewal', 'SEC:ALP:S06_S07:WB', 'SEC:ALP:S07_S08:WB', 2, '2027-01-04', NULL, 3) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A035', 'C006', 'Construction', 'SEC:ALP:S02_S03:WB', 'SEC:ALP:S03_S04:WB', 3, '2027-01-04', NULL, 1) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A036', 'C006', 'Construction', 'SEC:BET:S14_H01:EB', 'SEC:BET:S14_H01:EB', 7, '2027-05-31', NULL, 1) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A037', 'C006', 'Construction', 'SEC:BET:S15_S16:EB', 'SEC:BET:S16_S17:EB', 2, '2027-02-22', NULL, 1) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A038', 'C006', 'Construction', 'SEC:BET:S17_S18:EB', 'SEC:BET:S17_S18:EB', 3, '2027-01-18', 'A037', 3) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A039', 'C006', 'Construction', 'SEC:BET:S11_S12:WB', 'SEC:BET:S13_S14:WB', 7, '2027-02-22', NULL, 2) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A040', 'C007', 'Renewal', 'SEC:BET:H01_H02:EB', 'SEC:BET:S15_S16:EB', 7, '2027-03-29', NULL, 1) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A041', 'C007', 'Renewal', 'SEC:BET:S15_S16:EB', 'SEC:BET:S15_S16:EB', 2, '2027-03-15', NULL, 3) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A042', 'C007', 'Renewal', 'SEC:BET:S15_S16:EB', 'SEC:BET:S17_S18:EB', 3, '2027-06-07', NULL, 2) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A043', 'C007', 'Renewal', 'SEC:BET:H02_S15:EB', 'SEC:BET:S16_S17:EB', 2, '2027-03-29', NULL, 3) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A046', 'C007', 'Renewal', 'SEC:ALP:S05_S06:WB', 'SEC:ALP:S05_S06:WB', 5, '2027-03-01', NULL, 3) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A047', 'C008', 'Renewal', 'SEC:ALP:H02_S05:EB', 'SEC:ALP:S05_S06:EB', 2, '2027-03-29', NULL, 3) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A048', 'C008', 'Renewal', 'SEC:BET:S13_S14:EB', 'SEC:BET:S13_S14:EB', 3, '2027-01-04', NULL, 3) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A049', 'C008', 'Renewal', 'SEC:BET:H02_S15:WB', 'SEC:BET:S15_S16:WB', 5, '2027-02-22', 'A048', 2) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A050', 'C008', 'Renewal', 'SEC:ALP:S03_S04:WB', 'SEC:ALP:S04_H01:WB', 2, '2027-04-26', NULL, 3) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A051', 'C008', 'Renewal', 'SEC:BET:S17_S18:WB', 'SEC:BET:S17_S18:WB', 2, '2027-06-28', 'A050', 1) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A054', 'C009', 'Construction', 'SEC:ALP:S04_H01:EB', 'SEC:ALP:H02_S05:EB', 2, '2027-04-26', NULL, 2) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A055', 'C009', 'Construction', 'SEC:BET:S13_S14:EB', 'SEC:BET:H01_H02:EB', 1, '2027-04-19', NULL, 1) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A056', 'C009', 'Construction', 'SEC:ALP:H02_S05:WB', 'SEC:ALP:S06_S07:WB', 2, '2027-05-03', NULL, 2) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A057', 'C009', 'Construction', 'SEC:BET:H02_S15:EB', 'SEC:BET:S15_S16:EB', 7, '2027-04-12', NULL, 3) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A058', 'C010', 'Construction', 'SEC:ALP:S03_S04:WB', 'SEC:ALP:H01_H02:WB', 7, '2027-01-11', NULL, 3) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A059', 'C010', 'Construction', 'SEC:ALP:S06_S07:WB', 'SEC:ALP:S07_S08:WB', 7, '2027-04-05', NULL, 3) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A060', 'C010', 'Construction', 'SEC:BET:H02_S15:EB', 'SEC:BET:S15_S16:EB', 3, '2027-03-29', NULL, 2) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A061', 'C010', 'Construction', 'SEC:BET:H01_H02:EB', 'SEC:BET:H02_S15:EB', 7, '2027-01-25', NULL, 1) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A063', 'C010', 'Construction', 'SEC:BET:S14_H01:EB', 'SEC:BET:H01_H02:EB', 1, '2027-02-01', NULL, 3) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A064', 'C010', 'Construction', 'SEC:BET:S15_S16:WB', 'SEC:BET:S15_S16:WB', 1, '2027-04-19', NULL, 3) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A065', 'C011', 'Renewal', 'SEC:BET:S12_S13:WB', 'SEC:BET:S12_S13:WB', 1, '2027-05-10', NULL, 2) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A066', 'C011', 'Renewal', 'SEC:ALP:S02_S03:WB', 'SEC:ALP:S04_H01:WB', 1, '2027-06-21', 'A065', 3) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A069', 'C011', 'Renewal', 'SEC:ALP:S03_S04:WB', 'SEC:ALP:H01_H02:WB', 2, '2027-03-01', NULL, 2) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A070', 'C011', 'Renewal', 'SEC:ALP:S03_S04:WB', 'SEC:ALP:S04_H01:WB', 5, '2027-03-15', NULL, 1) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A071', 'C011', 'Renewal', 'SEC:BET:S15_S16:EB', 'SEC:BET:S16_S17:EB', 1, '2027-04-12', NULL, 1) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A072', 'C012', 'Construction', 'SEC:ALP:S04_H01:EB', 'SEC:ALP:H01_H02:EB', 1, '2027-06-07', NULL, 2) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A073', 'C012', 'Construction', 'SEC:BET:H01_H02:EB', 'SEC:BET:H02_S15:EB', 1, '2027-05-31', NULL, 3) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A074', 'C013', 'Renewal', 'SEC:ALP:H01_H02:EB', 'SEC:ALP:H01_H02:EB', 1, '2027-05-10', NULL, 2) ON CONFLICT (activity_id) DO NOTHING;
INSERT INTO activities (activity_id, contract_number, activity_type, start_location_id, end_location_id, total_accesses, planned_start_date, predecessor_activity_id, activity_priority) VALUES ('A075', 'C014', 'Construction', 'SEC:BET:H01_H02:WB', 'SEC:BET:H01_H02:WB', 1, '2027-06-14', NULL, 3) ON CONFLICT (activity_id) DO NOTHING;

-- 10. REBUILD 1D SPATIAL TOPOLOGY
SELECT rebuild_network_topology();
